### PR TITLE
backend structure

### PR DESCRIPTION
**Pull request by pkamano**

### CODE REVIEW

**Review by elysemontano — CHANGES_REQUESTED** [review]
Everything looks great, however, it looks like you are missing image in your schema and seeds which may present a problem when we start to connect the frontend to the backend.

**Comment by pkamano** [comment]
Hi Elyse!
During the lecture, Tricia left it out because she said that we would be utilizing the assets folder.

**Comment by pkamano** [comment]
added an image to the database and pushed it up to this branch

**Review by elysemontano — APPROVED** [review]
Looks good!

**Pull request merged**
